### ISSUE TITLE
Playground not working

### ISSUE THREAD

**Issue by riccardoferretti** [jamesmcnamara/shades#35] opened 2020-02-18 15:56 UTC
Hi James,
thanks for the great job on shades, I have been looking around for a lens library and so far yours seems the most promising.
I wanted to use the playground to investigate the API more, but I am getting the following error:

```
16:53 $ npx shades
npx: installed 1 in 5.55s
Welcome to the Shades playground!
All of the functions have been imported for you, and the store from the README is available as 'store' (creative, I know)
Enjoy!
shades> Cannot find module 'lodash'
store
ReferenceError: store is not defined
```

Also, just wanted to check how active the project is, as I have noticed little activity in the last year. Is it stable or have you been too busy to follow the project?

Thanks again for the amazing work!
-Riccardo

**Comment by jamesmcnamara** [comment] 2020-02-20 17:53
Ah sorry this is because you don't have lodash installed locally I'll see if I can add a workaround. 

Yes this library is stable and used in production. I push changes but very slowly.

**Comment by riccardoferretti** [comment] 2020-02-21 10:04
Sounds good, FYI I did try running that in a project folder that had lodash (in `node_modules`), as well as installing `lodash` globally. Both cases resulted in the issue above.

Also, once installed in the local `node_modules`, `npx shades` works fine.

**Comment by jamesmcnamara** [comment] 2020-02-27 08:32
Very odd. I'll take a look at this soon.

**Comment by virzen** [comment] 2020-04-07 17:45
This happens for me too, even when running in my project's directory, where `lodash` is available.

**Comment by virzen** [comment] 2020-04-07 18:11
Problem is gone when `shades` is actually installed into the project — then, `npx shades` works ok.

**Comment by jamesmcnamara** [comment] 2022-08-15 20:34
Closing this issue because I cannot reproduce and no new issues have come from it. Re-open if you can't get the playground to work.

**Closed by jamesmcnamara** 2022-08-15 20:34 UTC
